 
    {
        "csv": "VESC",
        "veld": 13,
        "as": "links",
        "smooth": False,
        "window": 15,
        "linestyle": "-",
        "marker": "None",
        "markersize": 3,
        "alpha": 0.95,
    },
     {
        "csv": "VESC",
        "veld": 13,
        "as": "links",
        "smooth": False,
        "window": 15,
        "linestyle": "-",
        "marker": "None",
        "markersize": 3,
        "alpha": 0.95,
        "factor": 1/7, #RPM reductiekastfactor / factor kan gebruikt worden om te delen of vermenigvuldigen. 
        "label_suffix": "(Reductiekast 7:1)", 
    },
    {
        "csv": "VESC",       
        "veld": 8,            
       "as": "rechts",         
       "smooth": False,       
       "window": 15,          
        "linestyle": "solid",  
        "linewidth": 2,        
       "marker": None,        
       "markersize": 3,       
       "alpha": 1.0,               
    },
     {
        "csv": "VESC",       
        "veld": 10,            
       "as": "rechts",         
       "smooth": False,       
       "window": 15,          
        "linestyle": "solid",  
        "linewidth": 2,        
       "marker": None,        
       "markersize": 3,       
       "alpha": 1.0,            
    },
     {
        "csv": "Accu",       
        "veld": 21,            
       "as": "rechts",         
       "smooth": False,       
       "window": 15,          
        "linestyle": "solid",  
        "linewidth": 2,        
       "marker": None,        
       "markersize": 3,       
       "alpha": 1.0,            
    },
     {
        "csv": "Master",       
        "veld": 18,            
       "as": "rechts",         
       "smooth": False,       
       "window": 15,          
        "linestyle": "solid",  
        "linewidth": 2,        
       "marker": None,        
       "markersize": 3,       
       "alpha": 1.0,    
       "factor": 0.98,          
       "label_suffix": "(Inclusief factor)",  
    },